# Generated by Django 5.2.11 on 2026-04-11 06:11

from django.db import migrations


def set_superusers(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    superuser_emails = [
        'kartik15.janki@gmail.com',
        'jatin15.janki@gmail.com',
    ]
    for email in superuser_emails:
        user = User.objects.filter(email=email).first()
        if not user:
            user = User.objects.filter(username=email).first()
        if user and not user.is_superuser:
            user.is_superuser = True
            user.save(update_fields=['is_superuser'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_approved_emailotp'),
    ]

    operations = [
        migrations.RunPython(set_superusers, migrations.RunPython.noop),
    ]
