# Generated by Django 5.2.11 on 2026-04-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cleanup_duplicate_otp_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefaultPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], max_length=20, unique=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Role Default Permissions',
                'verbose_name_plural': 'Role Default Permissions',
            },
        ),

    ]
