# Generated by Django 5.2.12 on 2026-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_roledefaultpermissions'),
    ]

    operations = [
        # Truncate any existing OTP values that exceed the new max_length of 4
        migrations.RunSQL(
            sql="UPDATE accounts_emailotp SET otp = LEFT(otp, 4) WHERE LENGTH(otp) > 4;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(max_length=4),
        ),
    ]
