# Generated by Django 5.1.7 on 2026-05-09 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_permission_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A human-readable label for this key.', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('given_to', models.CharField(blank=True, default='', help_text='Name or organisation of the key recipient.', max_length=150)),
                ('key_prefix', models.CharField(help_text='First 8 characters of the raw key (display only).', max_length=8)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 hex of the raw key.', max_length=64, unique=True)),
                ('page_scopes', models.JSONField(default=list, help_text='Which pages this key can access.')),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False, help_text='Allows POST, PUT, DELETE on scoped endpoints.')),
                ('can_comment', models.BooleanField(default=False, help_text='Allows PATCH only (limited write).')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
