# Generated by Django 5.1.7 on 2026-05-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_apikey'),
        ('workforce', '0012_alter_workforcemember_category_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='given_to_workforce',
            field=models.ForeignKey(blank=True, help_text='The workforce member this key is assigned to (tech dept).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='workforce.workforcemember'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='given_to',
            field=models.CharField(blank=True, default='', help_text='Display name of the key recipient.', max_length=150),
        ),
    ]
