# Generated by Django 5.1.7 on 2026-05-29 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_apikey_given_to_workforce'),
        ('core_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_companies',
            field=models.ManyToManyField(blank=True, related_name='accessible_users', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TENANT_OWNER', 'Tenant Owner'), ('COMPANY_ADMIN', 'Company Admin'), ('DEPARTMENT_HEAD', 'Department Head'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('VIEWER', 'Viewer'), ('admin', 'Legacy Admin'), ('manager', 'Legacy Manager'), ('staff', 'Legacy Staff')], default='STAFF', max_length=50),
        ),
    ]
