# Generated by Custom SaaS Migration Script

from django.db import migrations

def seed_default_tenant_and_migrate_users(apps, schema_editor):
    Tenant = apps.get_model('core_tenants', 'Tenant')
    Company = apps.get_model('core_tenants', 'Company')
    User = apps.get_model('accounts', 'User')

    # Only perform seeding/migration if there are users, or simply ensure a default exists
    if User.objects.exists():
        # 1. Create or get default Tenant
        default_tenant, _ = Tenant.objects.get_or_create(
            slug='default-tenant',
            defaults={'name': 'Default Tenant', 'is_active': True}
        )

        # 2. Create or get default Company
        default_company, _ = Company.objects.get_or_create(
            tenant=default_tenant,
            code='DEFAULT',
            defaults={'name': 'Default Company', 'is_active': True}
        )

        # 3. Migrate each user
        for user in User.objects.all():
            modified = False
            
            # Map legacy roles to new SaaS enterprise roles
            if user.role == 'admin':
                user.role = 'TENANT_OWNER'
                modified = True
            elif user.role == 'manager':
                user.role = 'MANAGER'
                modified = True
            elif user.role == 'staff':
                user.role = 'STAFF'
                modified = True

            # Assign tenant if currently null
            if not user.tenant_id:
                user.tenant = default_tenant
                modified = True

            # Assign active company if currently null
            if not user.active_company_id:
                user.active_company = default_company
                modified = True

            if modified:
                user.save()

            # Ensure default company is in accessible_companies ManyToMany list
            if not user.accessible_companies.filter(id=default_company.id).exists():
                user.accessible_companies.add(default_company)


def rollback_default_tenant_migration(apps, schema_editor):
    # Backward migrations can remain a safe no-op to prevent deleting historical data
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0013_user_accessible_companies_user_active_company_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_tenant_and_migrate_users, rollback_default_tenant_migration),
    ]
