# Generated by Django 5.1.7 on 2026-06-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_default_tenant_seed'),
        ('core_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this API Key is scoped to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core_tenants.tenant'),
        ),
    ]
