from django.urls import path

from .views import (
    BalanceSheetView,
    InvoiceListCreateView,
    InvoiceSettleView,
    BankAccountDetailView,
    BankAccountListView,
    BankImportConfirmView,
    BankImportPreviewView,
    BankTransactionBulkDeleteView,
    BankTransactionConvertView,
    BankTransactionDetailView,
    BankTransactionListView,
    JournalCreateView,
    LedgerListView,
    LedgerSummaryView,
    PendingExpenseApproveView,
    PendingExpenseListView,
    PendingExpenseRejectView,
    PendingExpenseSyncView,
    ProfitLossView,
    TrialBalanceView,
    AccountListView,
    ExpenseListView,
    ExpenseCreateView,
    IncomeListView,
    IncomeCreateView,
    FinanceDashboardView,
    OutstandingListView,
    OutstandingSettleView,
    OutstandingDashboardView,
    OutstandingReceiptView,
)


urlpatterns = [
    path('ledgers/', LedgerListView.as_view(), name='accounting-ledgers'),
    path('accounts/', AccountListView.as_view(), name='accounting-accounts'),
    path('expenses/', ExpenseListView.as_view(), name='accounting-expenses'),
    path('expenses/create/', ExpenseCreateView.as_view(), name='accounting-expense-create'),
    path('income/', IncomeListView.as_view(), name='accounting-income'),
    path('income/create/', IncomeCreateView.as_view(), name='accounting-income-create'),
    path('finance-dashboard/', FinanceDashboardView.as_view(), name='accounting-finance-dashboard'),
    path('journal/create/', JournalCreateView.as_view(), name='accounting-journal-create'),
    path('ledger-summary/', LedgerSummaryView.as_view(), name='accounting-ledger-summary'),
    path('trial-balance/', TrialBalanceView.as_view(), name='accounting-trial-balance'),
    path('profit-loss/', ProfitLossView.as_view(), name='accounting-profit-loss'),
    path('balance-sheet/', BalanceSheetView.as_view(), name='accounting-balance-sheet'),
    # Pending Expense endpoints
    path('pending-expenses/', PendingExpenseListView.as_view(), name='accounting-pending-expenses'),
    path('pending-expenses/sync/', PendingExpenseSyncView.as_view(), name='accounting-pending-expenses-sync'),
    path('pending-expenses/<int:pk>/approve/', PendingExpenseApproveView.as_view(), name='accounting-pending-expense-approve'),
    path('pending-expenses/<int:pk>/reject/', PendingExpenseRejectView.as_view(), name='accounting-pending-expense-reject'),
    # Outstanding endpoints
    path('outstandings/', OutstandingListView.as_view(), name='accounting-outstandings'),
    path('outstandings/dashboard/', OutstandingDashboardView.as_view(), name='accounting-outstandings-dashboard'),
    path('outstandings/<int:pk>/settle/', OutstandingSettleView.as_view(), name='accounting-outstanding-settle'),
    path('outstandings/<int:pk>/receipts/', OutstandingReceiptView.as_view(), name='accounting-outstanding-receipts'),
    # Invoice endpoints
    path('invoices/', InvoiceListCreateView.as_view(), name='accounting-invoices'),
    path('invoices/<int:pk>/settle/', InvoiceSettleView.as_view(), name='accounting-invoice-settle'),
    # Bank Statement Import (parse + confirm flow)
    path('bank-import/preview/', BankImportPreviewView.as_view(), name='accounting-bank-import-preview'),
    path('bank-import/confirm/', BankImportConfirmView.as_view(), name='accounting-bank-import-confirm'),
    # Banking Module
    path('bank-accounts/', BankAccountListView.as_view(), name='accounting-bank-accounts'),
    path('bank-accounts/<int:pk>/', BankAccountDetailView.as_view(), name='accounting-bank-account-detail'),
    path('bank-transactions/', BankTransactionListView.as_view(), name='accounting-bank-transactions'),
    path('bank-transactions/bulk-delete/', BankTransactionBulkDeleteView.as_view(), name='accounting-bank-transactions-bulk-delete'),
    path('bank-transactions/convert/', BankTransactionConvertView.as_view(), name='accounting-bank-transactions-convert'),
    path('bank-transactions/<int:pk>/', BankTransactionDetailView.as_view(), name='accounting-bank-transaction-detail'),
]
