# Generated by Django 5.1.7 on 2026-06-06 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0002_add_attributes_to_picklistitem'),
        ('orders', '0007_alter_order_company_alter_order_tenant_and_more'),
        ('products', '0020_product_products_pr_tenant__1281cc_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'company', 'order'], name='orders_orde_tenant__1d874e_idx'),
        ),
    ]
