# Generated by Django 5.1.7 on 2026-05-29 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tenant organization name.', max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this tenant is active.')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name.', max_length=255)),
                ('code', models.CharField(blank=True, default='', help_text='Internal company code.', max_length=50)),
                ('gst_number', models.CharField(blank=True, default='', help_text='Tax registration number.', max_length=15)),
                ('address', models.TextField(blank=True, default='', help_text='Postal address of the company.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this company is active.')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this company.', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code'), ('tenant', 'name')},
            },
        ),
    ]
