# Generated by Django 5.1.7 on 2026-06-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='external_shop_id',
            field=models.CharField(blank=True, default='', help_text='External shop ID for repair queue sync.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, help_text='Razorpay Customer ID for SaaS billing.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for SaaS billing.', max_length=255, null=True),
        ),
    ]
