# Generated by Django 5.1.7 on 2026-06-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0002_tenant_external_shop_id_tenant_razorpay_customer_id_and_more'),
        ('industries', '0001_initial'),
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='The primary industry vertical for this tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='industries.industry'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The SaaS plan this tenant is subscribed to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='platform_admin.plan'),
        ),
    ]
