# Generated by Django 5.1.7 on 2026-06-04 06:58

from django.db import migrations


def migrate_tenants_to_jewellery(apps, schema_editor):
    Tenant = apps.get_model('core_tenants', 'Tenant')
    Industry = apps.get_model('industries', 'Industry')
    
    try:
        jewellery = Industry.objects.get(code='jewellery')
        Tenant.objects.filter(industry__isnull=True).update(industry=jewellery)
    except Industry.DoesNotExist:
        pass

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0003_tenant_industry_tenant_plan'),
        ('industries', '0002_seed_jewellery'),
    ]

    operations = [
        migrations.RunPython(migrate_tenants_to_jewellery, reverse_migrate)
    ]
