# Generated by Django 5.1.7 on 2026-06-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0004_migrate_tsf'),
        ('saas_billing', '0002_platformauditrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The SaaS plan this tenant is subscribed to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='saas_billing.plan'),
        ),
    ]
