# Generated by Django 5.1.7 on 2026-06-05 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0005_alter_tenant_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active_trial', 'Active Trial'), ('active_paid', 'Active Paid'), ('trial_expired', 'Trial Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending_verification', max_length=50),
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_logo', models.URLField(blank=True, default='', max_length=500)),
                ('primary_color', models.CharField(blank=True, default='#000000', max_length=20)),
                ('secondary_color', models.CharField(blank=True, default='#FFFFFF', max_length=20)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company_website', models.URLField(blank=True, default='', max_length=500)),
                ('company_phone', models.CharField(blank=True, default='', max_length=50)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='core_tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
