# Generated by Django 5.1.7 on 2026-06-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0006_tenant_onboarding_completed_tenant_onboarding_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active_trial', 'Active Trial'), ('active_paid', 'Active Paid'), ('trial_expired', 'Trial Expired'), ('grace_period', 'Grace Period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending_verification', max_length=50),
        ),
    ]
