# Generated by Django 5.1.7 on 2026-06-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0007_alter_tenant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active_trial', 'Active Trial'), ('active_paid', 'Active Paid'), ('trial_expired', 'Trial Expired'), ('grace_period', 'Grace Period'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending_verification', max_length=50),
        ),
    ]
