# Generated by Django 5.2.12 on 2026-03-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_replace_stone_flat_with_stone_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plating_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
