# Generated by Django 5.2.12 on 2026-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, default='cts', max_length=30),
        ),
    ]
