# Generated by Django 5.2.12 on 2026-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_weight_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableColumnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(choices=[('live_stock', 'Live Stock Situation'), ('stone_info', 'Stone Info'), ('plating_info', 'Plating Info')], max_length=40)),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['table_type', 'order'],
                'unique_together': {('table_type', 'key')},
            },
        ),
    ]
