# Generated by Django 5.2.12 on 2026-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_name_allow_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invoice_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Per-unit price used when auto-calculating invoice totals from picklist orders', max_digits=14),
        ),
    ]
