# Generated by Django 5.1.7 on 2026-06-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('products', '0017_add_invoice_price_to_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='tablecolumnconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='channel',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='collection',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='material',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tablecolumnconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='master_sku',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'master_sku')},
        ),
        migrations.AlterUniqueTogether(
            name='tablecolumnconfig',
            unique_together={('tenant', 'table_type', 'key')},
        ),
    ]
