# Generated by Django 5.1.7 on 2026-06-01 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('products', '0019_alter_category_tenant_alter_channel_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'company', 'is_active'], name='products_pr_tenant__1281cc_idx'),
        ),
    ]
