# Generated by Django 5.1.7 on 2026-06-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0003_tenant_industry_tenant_plan'),
        ('products', '0020_product_products_pr_tenant__1281cc_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
                ('company', models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', help_text='Category name this applies to. Blank means all categories.', max_length=120)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='products.productattribute')),
                ('company', models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sku'],
                'unique_together': {('tenant', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
                ('company', models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
