# Generated by Django 5.2.12 on 2026-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_bulk_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_refs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
