# Generated by Django 5.2.12 on 2026-05-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_add_order_refs_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingexpense',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
