# Generated by Django 5.1.7 on 2026-06-03 07:41

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_pendingexpense_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='income',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='journalitemattachment',
            name='file',
            field=models.FileField(upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='outstandingreceipt',
            name='file',
            field=models.FileField(upload_to=common.storage.tenant_directory_path),
        ),
    ]
