# Generated by Django 5.2.11 on 2026-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesk', '0003_chat_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel & Transport'), ('food', 'Meals & Entertainment'), ('office_supplies', 'Office Supplies'), ('software', 'Software & Subscriptions'), ('equipment', 'Equipment & Hardware'), ('marketing', 'Marketing & Advertising'), ('training', 'Training & Development'), ('courier', 'Courier & Shipping'), ('utilities', 'Utilities'), ('maintenance', 'Repairs & Maintenance'), ('vendor', 'Vendor Payments'), ('misc', 'Miscellaneous'), ('client_entertainment', 'Client Entertainment'), ('other', 'Other')], default='misc', max_length=30),
        ),
    ]
