# Generated by Django 5.1.7 on 2026-06-03 07:41

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesk', '0005_diaryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='file',
            field=models.FileField(upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='mydesknoteattachment',
            name='file',
            field=models.FileField(upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='payrollpaymentrecord',
            name='payslip_pdf',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='personaltodoattachment',
            name='file',
            field=models.FileField(upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='personaltodoitem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.tenant_directory_path),
        ),
    ]
