# Generated by Django 5.1.7 on 2026-06-03 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0002_tenant_external_shop_id_tenant_razorpay_customer_id_and_more'),
        ('saas_billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('webhook_failure', 'Webhook Failure'), ('payment_failure', 'Payment Failure'), ('entitlement_denial', 'Entitlement Denial'), ('storage_drift_corrected', 'Storage Drift Corrected'), ('usage_aggregation_failure', 'Usage Aggregation Failure'), ('subscription_upgrade', 'Subscription Upgrade'), ('subscription_downgrade', 'Subscription Downgrade'), ('subscription_cancelled', 'Subscription Cancelled'), ('subscription_renewed', 'Subscription Renewed')], max_length=50)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='saas_billin_tenant__f3fa5e_idx'),
        ),
        migrations.AddIndex(
            model_name='planentitlement',
            index=models.Index(fields=['plan', 'key'], name='saas_billin_plan_id_1fb94e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='saas_billin_status_4e9bb7_idx'),
        ),
        migrations.AddField(
            model_name='platformauditrecord',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformauditrecord',
            name='new_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='saas_billing.plan'),
        ),
        migrations.AddField(
            model_name='platformauditrecord',
            name='old_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='saas_billing.plan'),
        ),
        migrations.AddField(
            model_name='platformauditrecord',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to='saas_billing.subscription'),
        ),
        migrations.AddField(
            model_name='platformauditrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to='core_tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='platformauditrecord',
            index=models.Index(fields=['event_type', 'created_at'], name='saas_billin_event_t_1cfc9a_idx'),
        ),
    ]
