# Generated by Django 5.1.7 on 2026-06-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0003_upgraderequestevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_trial_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='requires_payment_method',
            field=models.BooleanField(default=False),
        ),
    ]
