# Generated by Django 5.1.7 on 2026-06-05 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0006_tenant_onboarding_completed_tenant_onboarding_step_and_more'),
        ('saas_billing', '0004_plan_is_public_plan_is_trial_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgraderequestevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='upgraderequestevent',
            name='saas_billin_timesta_0bbd01_idx',
        ),
        migrations.RenameField(
            model_name='upgraderequestevent',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='upgraderequestevent',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='upgraderequestevent',
            index=models.Index(fields=['created_at'], name='saas_billin_created_201c26_idx'),
        ),
    ]
