# Generated by Django 5.2.11 on 2026-05-09 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='accounting_payroll_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='attendance_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='attendance_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_attendance_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='bank_file_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='bank_file_generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_bank_file_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='calculation_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='calculation_run_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_calculations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='exception_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='exception_report',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='payslips_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='payslips_generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_payslip_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='sent_to_finance_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='sent_to_finance_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_finance_sends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollpaymentrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('HR Approved', 'HR Approved'), ('Sent to Finance', 'Sent to Finance'), ('Paid', 'Paid'), ('On Hold', 'On Hold')], default='Paid', max_length=20),
        ),
    ]
