# Generated by Django 5.2.11 on 2026-05-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_payrollrun_accounting_payroll_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='payslip_pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
