# Generated by Django 5.1.7 on 2026-05-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_payrollpaymentrecord_payslip_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollpaymentrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('HR Approved', 'HR Approved'), ('Sent to Finance', 'Sent to Finance'), ('Finance Approved', 'Finance Approved'), ('Paid', 'Paid'), ('On Hold', 'On Hold')], default='Paid', max_length=20),
        ),
    ]
