# Generated by Django 5.1.7 on 2026-06-03 07:41

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_payrollpaymentrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.tenant_directory_path),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.tenant_directory_path),
        ),
    ]
