# Generated by Django 5.1.7 on 2026-06-04 06:57

from django.db import migrations


def create_default_industries(apps, schema_editor):
    Industry = apps.get_model('industries', 'Industry')
    IndustryTemplate = apps.get_model('industries', 'IndustryTemplate')
    IndustryWorkflow = apps.get_model('industries', 'IndustryWorkflow')
    InventoryDefinition = apps.get_model('industries', 'InventoryDefinition')
    
    # 1. Jewellery
    jewellery, _ = Industry.objects.get_or_create(
        code='jewellery',
        defaults={'name': 'Jewellery', 'description': 'Fine Jewellery Manufacturing and Retail'}
    )
    
    IndustryTemplate.objects.get_or_create(
        industry=jewellery,
        defaults={'default_sku_format': '{CATEGORY}-{ID}-{ATTR:Purity}'}
    )
    
    InventoryDefinition.objects.get_or_create(
        industry=jewellery,
        code='stone',
        defaults={'name': 'Stone Inventory', 'tracking_dimensions': [{'code': 'weight', 'label': 'Weight (cts)'}]}
    )

def reverse_industries(apps, schema_editor):
    Industry = apps.get_model('industries', 'Industry')
    Industry.objects.filter(code='jewellery').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_industries, reverse_industries)
    ]
