# Generated by Django 5.1.7 on 2026-06-04 07:31

from django.db import migrations


def seed_industries(apps, schema_editor):
    Industry = apps.get_model('industries', 'Industry')
    IndustryTemplate = apps.get_model('industries', 'IndustryTemplate')
    InventoryDefinition = apps.get_model('industries', 'InventoryDefinition')

    industry_data = [
        {
            'code': 'jewellery', 'name': 'Jewellery',
            'sku_format': 'RING-{ID}-{ATTR:Purity}',
            'attributes': ['Purity', 'Weight', 'Stone'],
            'inventory': [
                {'code': 'stone', 'name': 'Stone Inventory', 'dims': ['Weight', 'Purity']},
                {'code': 'metal', 'name': 'Metal Inventory', 'dims': ['Weight', 'Purity']}
            ]
        },
        {
            'code': 'fashion', 'name': 'Fashion',
            'sku_format': '{CATEGORY}-{ATTR:Color}-{ATTR:Size}',
            'attributes': ['Size', 'Color', 'Fabric'],
            'inventory': [
                {'code': 'fabric', 'name': 'Fabric Roll', 'dims': ['Color', 'Size']},
                {'code': 'garment', 'name': 'Garment Stock', 'dims': ['Color', 'Size']}
            ]
        },
        {
            'code': 'perfume', 'name': 'Perfume',
            'sku_format': '{CATEGORY}-{ATTR:Fragrance}-{ATTR:Volume}',
            'attributes': ['Volume', 'Fragrance', 'Batch'],
            'inventory': [
                {'code': 'bottle', 'name': 'Bottle Inventory', 'dims': ['Batch', 'Expiry']}
            ]
        },
        {
            'code': 'home_decor', 'name': 'Home Decor',
            'sku_format': '{CATEGORY}-{ATTR:Material}-{ID}',
            'attributes': ['Material', 'Dimension', 'Color'],
            'inventory': [
                {'code': 'raw_material', 'name': 'Raw Material', 'dims': ['Material']},
                {'code': 'finished_goods', 'name': 'Finished Goods', 'dims': ['Dimension']}
            ]
        },
        {
            'code': 'generic', 'name': 'Generic Commerce',
            'sku_format': '{CATEGORY}-{ID}',
            'attributes': [],
            'inventory': [
                {'code': 'stock', 'name': 'General Stock', 'dims': ['Location']}
            ]
        }
    ]

    for data in industry_data:
        ind, _ = Industry.objects.get_or_create(code=data['code'], defaults={'name': data['name']})
        
        # Update or create template
        template, _ = IndustryTemplate.objects.get_or_create(industry=ind)
        template.default_sku_format = data['sku_format']
        # Store default attributes in config since ProductAttribute is tenant-scoped
        template.config = {'default_attributes': data['attributes']}
        template.save()

        # Seed Inventory Definitions
        for inv in data['inventory']:
            InventoryDefinition.objects.get_or_create(
                industry=ind,
                code=inv['code'],
                defaults={'name': inv['name'], 'tracking_dimensions': inv['dims']}
            )

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0002_seed_jewellery'),
    ]

    operations = [
        migrations.RunPython(seed_industries, reverse_seed)
    ]
