# Generated by Django 5.1.7 on 2026-06-01 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('customers', '0003_alter_customer_company_alter_customer_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'company', 'status'], name='customers_c_tenant__beb987_idx'),
        ),
    ]
