# Generated by Django 5.2.12 on 2026-03-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kyc_verification_fields'),
    ]

    operations = [
        # Use IF EXISTS so this migration is safe whether or not 0002 was
        # previously applied to this database (handles both fresh and
        # already-migrated environments).
        # Replaced PostgreSQL-specific RunSQL (with DROP COLUMN IF EXISTS) 
        # with standard Django operations since we are using SQLite.
        migrations.RemoveField(model_name='kycrecord', name='aadhaar_number'),
        migrations.RemoveField(model_name='kycrecord', name='aadhaar_status'),
        migrations.RemoveField(model_name='kycrecord', name='gst_number'),
        migrations.RemoveField(model_name='kycrecord', name='gst_status'),
        migrations.RemoveField(model_name='kycrecord', name='pan_number'),
        migrations.RemoveField(model_name='kycrecord', name='pan_status'),
    ]
