# Generated by Django 5.1.7 on 2026-06-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('kyc', '0003_remove_kycrecord_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
    ]
