# Generated by Django 5.2.12 on 2026-03-28 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_stock_type_to_inventorytransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stone_type', models.CharField(blank=True, default='', max_length=120)),
                ('species', models.CharField(blank=True, default='', max_length=120)),
                ('variety', models.CharField(blank=True, default='', max_length=120)),
                ('color', models.CharField(blank=True, default='', max_length=120)),
                ('quality', models.CharField(blank=True, default='', max_length=120)),
                ('wax_setting', models.BooleanField(default=False)),
                ('dos', models.TextField(blank=True, default='')),
                ('donts', models.TextField(blank=True, default='')),
                ('shape', models.CharField(blank=True, default='', max_length=120)),
                ('length', models.CharField(blank=True, default='', max_length=60)),
                ('width', models.CharField(blank=True, default='', max_length=60)),
                ('height', models.CharField(blank=True, default='', max_length=60)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('weight_cts', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StoneStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_added', models.DecimalField(decimal_places=3, max_digits=12)),
                ('weight_cts_added', models.DecimalField(decimal_places=4, max_digits=12)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.stoneitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
