# Generated by Django 5.2.12 on 2026-03-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stoneitem_stonestockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneitem',
            name='cut',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='stonestockentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stonestockentry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stonestockentry',
            name='price_by',
            field=models.CharField(choices=[('pcs', 'By Piece'), ('weight', 'By Weight')], default='pcs', max_length=10),
        ),
    ]
