# Generated by Django 5.2.12 on 2026-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_productinventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
