# Generated by Django 5.2.12 on 2026-04-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_log_and_finding_inventory_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolitem',
            name='min_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
