# Generated by Django 5.2.12 on 2026-04-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_min_level_to_toolitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='findinginventorytransaction',
            name='usage',
            field=models.CharField(blank=True, default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='otheritem',
            name='used_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='usage',
            field=models.CharField(blank=True, default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='stoneitem',
            name='used_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stonetransaction',
            name='usage',
            field=models.CharField(blank=True, default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='toolitem',
            name='used_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='inventory_type',
            field=models.CharField(choices=[('tools', 'Tools'), ('machines', 'Machines'), ('others', 'Others'), ('stone', 'Stone'), ('finding', 'Finding'), ('product', 'Product')], max_length=20),
        ),
    ]
