# Generated by Django 5.2.12 on 2026-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_add_used_qty_and_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='findinginventoryitem',
            name='used_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
