# Generated by Django 5.2.12 on 2026-04-20 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_used_qty_to_finding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerequest',
            name='inventory_type',
            field=models.CharField(choices=[('tools', 'Tools'), ('machines', 'Machines'), ('others', 'Others'), ('stone', 'Stone'), ('finding', 'Finding'), ('product', 'Product'), ('die', 'Die')], max_length=20),
        ),
        migrations.CreateModel(
            name='DieInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('die_code', models.CharField(max_length=120, unique=True)),
                ('image', models.TextField(blank=True, default='')),
                ('master_skus', models.JSONField(blank=True, default=list)),
                ('designer_skus', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('wax_setting', models.CharField(blank=True, default='', max_length=60)),
                ('casting', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('used_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('min_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DieTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_date', models.DateField()),
                ('die_code', models.CharField(blank=True, default='', max_length=120)),
                ('txn_type', models.CharField(choices=[('received', 'Received'), ('issued', 'Issued')], max_length=10)),
                ('inventory_type', models.CharField(blank=True, default='', max_length=60)),
                ('master_sku', models.CharField(blank=True, default='', max_length=120)),
                ('designer_sku', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('wax_setting', models.CharField(blank=True, default='', max_length=60)),
                ('casting', models.CharField(blank=True, default='', max_length=60)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('received_from', models.CharField(blank=True, default='', max_length=255)),
                ('issued_to', models.CharField(blank=True, default='', max_length=255)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('activity_status', models.CharField(blank=True, default='', max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('die', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.dieinventoryitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-txn_date', '-created_at'),
            },
        ),
    ]
