# Generated by Django 5.2.12 on 2026-04-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_die_inventory_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneitem',
            name='min_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
