# Generated by Django 5.1.7 on 2026-05-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_toolitem_restructure_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinventoryitem',
            name='casting_min',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='casting_wip',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='filling_current',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='filling_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='filling_min',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='filling_wip',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='final_polish_current',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='final_polish_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='final_polish_min',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='final_polish_wip',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='hand_setting_current',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='hand_setting_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='hand_setting_min',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='hand_setting_wip',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='plating_current',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='plating_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='plating_min',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='plating_wip',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='pre_polish_current',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='pre_polish_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='pre_polish_min',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='pre_polish_wip',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='wax_piece_min',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='wax_piece_wip',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='wax_setting_min',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='wax_setting_wip',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
