# Generated by Django 5.1.7 on 2026-06-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('inventory', '0021_repairbatch_repairitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinventoryitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='dieinventoryitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dietransaction',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='dietransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='findinginventoryitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='findinginventoryitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='findinginventorytransaction',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='findinginventorytransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='machineitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='machineitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='otheritem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='otheritem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='picklistgroup',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='picklistgroup',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='picklistitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='picklistitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='productinventoryitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='productinventoryitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='productinventorytransaction',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='productinventorytransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='repairbatch',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='repairbatch',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='repairitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='repairitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stoneitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='stoneitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stonestockentry',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='stonestockentry',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stonetransaction',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='stonetransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='toolitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='toolitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='dieinventoryitem',
            name='die_code',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='picklistgroup',
            name='group_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='picklistgroup',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='repairbatch',
            name='batch_no',
            field=models.CharField(help_text='e.g. Repair-YYYY-MM-DD', max_length=120),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='repair_item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='dieinventoryitem',
            unique_together={('tenant', 'die_code')},
        ),
        migrations.AlterUniqueTogether(
            name='picklistgroup',
            unique_together={('tenant', 'group_id'), ('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='repairbatch',
            unique_together={('tenant', 'batch_no')},
        ),
        migrations.AlterUniqueTogether(
            name='repairitem',
            unique_together={('tenant', 'repair_item_id')},
        ),
    ]
