# Generated by Django 5.1.7 on 2026-06-01 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('inventory', '0022_dieinventoryitem_company_dieinventoryitem_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieinventoryitem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='dieinventoryitem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='dietransaction',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='dietransaction',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='findinginventoryitem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='findinginventoryitem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='findinginventorytransaction',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='findinginventorytransaction',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='machineitem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='machineitem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='picklistgroup',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='picklistgroup',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='picklistitem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='picklistitem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='productinventoryitem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='productinventoryitem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='productinventorytransaction',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='productinventorytransaction',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='repairbatch',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='repairbatch',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='stoneitem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='stoneitem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='stonestockentry',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='stonestockentry',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='stonetransaction',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='stonetransaction',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='toolitem',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='toolitem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
    ]
