# Generated by Django 5.1.7 on 2026-06-01 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('inventory', '0023_alter_dieinventoryitem_company_and_more'),
        ('products', '0019_alter_category_tenant_alter_channel_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tenant', 'company', 'txn_type'], name='inventory_i_tenant__bdddb5_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['tenant', 'company', 'status'], name='inventory_i_tenant__61a918_idx'),
        ),
    ]
