# Generated by Django 5.1.7 on 2026-06-05 05:03

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0002_add_attributes_to_picklistitem'),
        ('inventory', '0026_picklistitem_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
