# Generated by Django 5.1.7 on 2026-06-03 07:41

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('inventory', '0024_alter_inventorytransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dieinventoryitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['master_skus'], name='inventory_d_master__1b5fea_gin'),
        ),
        migrations.AddIndex(
            model_name='repairbatch',
            index=models.Index(fields=['tenant', 'company', 'confirmed'], name='inventory_r_tenant__e6dc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='repairitem',
            index=models.Index(fields=['tenant', 'company', 'repair_stage', 'confirmed'], name='inventory_r_tenant__ebf043_idx'),
        ),
    ]
