# Generated by Django 5.1.7 on 2026-06-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_dieinventoryitem_inventory_d_master__1b5fea_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistitem',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic industry-specific attributes required for picking'),
        ),
    ]
