# Generated by Django 5.1.7 on 2026-06-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0005_alter_tenant_plan'),
        ('platform_admin', '0001_initial'),
        ('saas_billing', '0002_platformauditrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='saas_billing.plan'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
