# Generated by Django 5.1.7 on 2026-06-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0002_alter_planfeature_plan_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_beta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='min_plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
