# Generated by Django 5.1.7 on 2026-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0003_seed_all_industries'),
        ('platform_admin', '0003_feature_category_feature_icon_feature_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='If empty, applies to all industries.', related_name='features', to='industries.industry'),
        ),
    ]
