# Generated by Django 5.2.11 on 2026-03-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_generic_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="contact",
            field=models.CharField(
                blank=True, help_text="Contact number for job", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="issued_by",
            field=models.CharField(
                blank=True, help_text="Name of person issuing the job", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="issued_to",
            field=models.CharField(
                blank=True,
                help_text="Name of person/vendor job is issued to",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes for the job"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="schedule",
            field=models.DateField(
                blank=True, help_text="Scheduled completion date", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="work_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("In-House", "In-House"),
                    ("Contract", "Contract"),
                    ("Job Work", "Job Work"),
                ],
                help_text="Work type for generic jobs",
                max_length=50,
            ),
        ),
    ]
