# Generated by Django 5.2.11 on 2026-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_contact_job_issued_by_job_issued_to_job_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="uploaded_files",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of uploaded files (photos, documents, etc.)",
            ),
        ),
    ]
