# Generated by Django 5.2.11 on 2026-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_uploaded_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(blank=True, default="Untitled Job", max_length=255),
        ),
    ]
