# Generated by Django 5.2.12 on 2026-04-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_machineitem_otheritem_toolitem'),
        ('jobs', '0006_job_voucher_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_process', 'In Process'), ('awaiting', 'Awaiting'), ('completed', 'Completed')], default='pending', help_text='Voucher approval workflow status', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When voucher was approved', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='approved_by',
            field=models.CharField(blank=True, default='', help_text='Who approved this voucher', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='batch_id',
            field=models.CharField(blank=True, default='', help_text='Groups vouchers from same bulk creation', max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='department_order',
            field=models.PositiveIntegerField(default=0, help_text='Sequence order in department pipeline (0=first)'),
        ),
        migrations.AddField(
            model_name='job',
            name='picklist_group',
            field=models.ForeignKey(blank=True, help_text='Picklist this voucher was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='inventory.picklistgroup'),
        ),
    ]
