# Generated by Django 5.2.12 on 2026-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_approval_status_job_approved_at_job_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='received_by',
            field=models.CharField(blank=True, default='', help_text='Who received/accepted the job', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='received_rows',
            field=models.JSONField(blank=True, default=list, help_text='Audit log of all receive events [{timestamp, received_by, is_partial, rows}]'),
        ),
        migrations.AlterField(
            model_name='job',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_process', 'In Process'), ('awaiting', 'Awaiting'), ('partially_complete', 'Partially Completed'), ('completed', 'Completed')], default='pending', help_text='Voucher approval workflow status', max_length=30),
        ),
    ]
