# Generated by Django 5.1.7 on 2026-05-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_stone_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='stone_rows',
            field=models.JSONField(blank=True, default=list, help_text='Stone issuance rows'),
        ),
    ]
