# Generated by Django 5.2.11 on 2026-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_stone_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='voucher_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Re-Issue', 'Re-Issue'), ('Repair', 'Repair')], default='New', help_text='New, Re-Issue or Repair voucher', max_length=20),
        ),
    ]
