# Generated by Django 5.1.7 on 2026-06-01 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('jobs', '0014_job_company_job_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
    ]
