# Generated by Django 5.1.7 on 2026-06-01 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('inventory', '0024_alter_inventorytransaction_options_and_more'),
        ('jobs', '0015_alter_job_company_alter_job_tenant'),
        ('products', '0019_alter_category_tenant_alter_channel_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'company', 'status'], name='jobs_job_tenant__23f707_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'company', 'approval_status'], name='jobs_job_tenant__6b7164_idx'),
        ),
    ]
