# Generated by Django 5.1.7 on 2026-06-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_job_options_job_jobs_job_tenant__23f707_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='findings_rows',
            field=models.JSONField(blank=True, default=list, help_text='Findings rows'),
        ),
    ]
