# Generated by Django 5.2.12 on 2026-03-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='dead_weight',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='finding',
            name='design_material',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='finding',
            name='finding_stage',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='finding',
            name='image3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='finding',
            name='material',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='finding',
            name='mechanism',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='finding',
            name='mold_qty_per_die',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='finding',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='finding',
            name='plating_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='finding',
            name='polish',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='finding',
            name='primary_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='finding',
            name='reference_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='finding',
            name='stone_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='finding',
            name='total_measurements',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='finding',
            name='tracking_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
