# Generated by Django 5.2.11 on 2026-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_workforcemember_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcemember',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
