# Generated by Django 5.2.11 on 2026-04-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0004_add_category_working_style_banking"),
    ]

    operations = [
        migrations.AddField(
            model_name="workforcemember",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
