# Generated by Django 5.2.11 on 2026-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_workforcemember_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcemember',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
