# Generated by Django 5.2.12 on 2026-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_add_apoorva_workforce_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcemember',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
