# Generated by Django 5.2.12 on 2026-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_add_document_urls_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforcemember',
            name='aadhaar_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='workforcemember',
            name='pan_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='workforcemember',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
