# Generated by Django 5.1.7 on 2026-06-01 08:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_default_tenant_company(apps, schema_editor):
    Tenant = apps.get_model('core_tenants', 'Tenant')
    Company = apps.get_model('core_tenants', 'Company')
    WorkforceMember = apps.get_model('workforce', 'WorkforceMember')

    tenant = Tenant.objects.filter(slug='default').first()
    if not tenant:
        tenant = Tenant.objects.create(slug='default', name='Default Tenant', is_active=True)

    company = Company.objects.filter(tenant=tenant, name='Default Company').first()
    if not company:
        company = Company.objects.create(tenant=tenant, name='Default Company', is_active=True)

    WorkforceMember.objects.filter(tenant__isnull=True).update(tenant=tenant)
    WorkforceMember.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('workforce', '0012_alter_workforcemember_category_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcemember',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company_related', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='workforcemember',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core_tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='workforcemember',
            name='barcode_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='workforcemember',
            unique_together={('tenant', 'barcode_number')},
        ),
        migrations.RunPython(backfill_default_tenant_company, migrations.RunPython.noop),
    ]
