# Generated by Django 5.1.7 on 2026-06-03 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_initial'),
        ('workforce', '0014_alter_workforcemember_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workforcemember',
            index=models.Index(fields=['tenant', 'company', 'active'], name='workforce_w_tenant__18df23_idx'),
        ),
    ]
