# Generated by Django 5.1.7 on 2026-06-06 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0002_add_attributes_to_picklistitem'),
        ('workforce', '0015_fix_mismatched_tenants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
