# Generated by Django 5.2.12 on 2026-04-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deletionlog',
            new_name='common_dele_app_lab_b03825_idx',
            old_name='common_dele_app_lab_idx',
        ),
    ]
