# Generated by Django 5.2.12 on 2026-04-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_common_dele_app_lab_idx_common_dele_app_lab_b03825_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionlog',
            name='deleted_by_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
