# Generated by Django 5.1.7 on 2026-05-04 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_deleted_by_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=300)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('login', 'Login')], db_index=True, max_length=20)),
                ('sheet', models.CharField(choices=[('product', 'Product'), ('designer', 'Designer'), ('finding', 'Finding'), ('workforce', 'Workforce'), ('customer', 'Customer'), ('kyc', 'KYC'), ('job', 'Job'), ('inventory', 'Inventory'), ('order', 'Order'), ('accounting', 'Accounting'), ('hr', 'HR'), ('auth', 'Auth'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('object_repr', models.CharField(blank=True, default='', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('rows_affected', models.PositiveIntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'sheet'], name='common_acti_timesta_c08076_idx'), models.Index(fields=['user', 'timestamp'], name='common_acti_user_id_30cf0c_idx'), models.Index(fields=['action', 'timestamp'], name='common_acti_action_a040aa_idx')],
            },
        ),
    ]
