<<<<<<< HEAD
# Generated by Django 5.1.7 on 2026-06-03 07:41
=======
# Generated by Django 5.1.7 on 2026-06-06 09:41
>>>>>>> f331d6ce58a1d488eb8e481944fa6e96fa513b37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_activitylog'),
        ('core_tenants', '0002_add_attributes_to_picklistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='deletionlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to='core_tenants.company'),
        ),
        migrations.AddField(
            model_name='deletionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to='core_tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', 'company'], name='common_acti_tenant__337480_idx'),
        ),
        migrations.AddIndex(
            model_name='deletionlog',
            index=models.Index(fields=['tenant', 'company'], name='common_dele_tenant__40589b_idx'),
        ),
    ]
