# Generated by Django 5.2.12 on 2026-03-20 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('image', models.TextField(blank=True, default='')),
                ('tdm_file', models.TextField(blank=True, default='')),
                ('stl_file', models.TextField(blank=True, default='')),
                ('tdm_status', models.CharField(blank=True, default='', max_length=255)),
                ('stl_status', models.CharField(blank=True, default='', max_length=255)),
                ('render_status', models.CharField(blank=True, default='', max_length=255)),
                ('print_3d_status', models.CharField(blank=True, default='', max_length=255)),
                ('die_entries', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
