# Generated by Django 5.2.12 on 2026-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designersheet',
            name='cpx_dead_weight',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='design_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='design_material',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='design_motive_size',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='die_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='findings_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='master_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='mechanism',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='mold_qty_per_die',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='rendered_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='stone_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='technical_drawing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='total_design_measurements',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
