# Generated by Django 5.2.12 on 2026-03-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0003_add_design_stage_and_extra_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='designersheet',
            name='tracking_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
