# Generated by Django 5.2.12 on 2026-03-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0004_add_tracking_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designersheet',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=60, unique=True),
        ),
    ]
