# Generated by Django 5.2.12 on 2026-03-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0005_sku_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='designersheet',
            name='enamel',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='designersheet',
            name='setting_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
