# Generated by Django 5.2.12 on 2026-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0006_add_setting_type_enamel'),
    ]

    operations = [
        migrations.AddField(
            model_name='designersheet',
            name='designer_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
