# Generated by Django 5.2.12 on 2026-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0009_add_plating_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designersheet',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=60, unique=True, verbose_name='Designer SKU'),
        ),
    ]
